### ISSUE TITLE
Inline calendar has a day highlighted when you change months.

### ISSUE THREAD

**Issue by Emnalyeriar** [kbwood/datepick#28]
When initializing this plugin as a calendar it highlighted the first day of the month as it would be the actual date. It is also visible on the datepicker [homepage](http://keith-wood.name/datepick.html) in the inline calendar. When you change months it always highlights the actual day number in the given month. The highlight disappears then you hover over the calendar.

I fixed this by removing 'renderer.highlightedClass' in line 2077.

**Comment by kbwood** [comment]
The date is highlighted to allow access via the keyboard. It shows which date would be selected as you move about the calendar.

**Comment by touhonoob** [comment]
@kbwood Hi, Is there a way to disable the highlight?

**Comment by kbwood** [comment]
The styling is controlled through CSS on _.datepick-month td .datepick-highlight_ so you change it to whatever you want.
