### ISSUE TITLE
Multiple Dates select is broken?

### ISSUE THREAD

**Issue by boynet** [kbwood/datepick#35]
see the demo in: http://keith-wood.name/datepick.html#multi

after clicking on  dates from the middle or rightest calendar the selection not working any more, and clicking on them is like clicking on the "next month" button

checked on chrome 48.0.2564.116

**Comment by kbwood** [comment]
Do you mean the three months inline at the bottom of that section? You can only select three dates, so after doing so you no longer mark dates as selected but do continue to navigate through the calendar.

**Comment by boynet** [comment]
you are right sorry, its confusing because it's navigate through the calendar even if its select the date

 is there an option to disable the navigation when clicking on dates?

**Comment by kbwood** [comment]
You could try overriding the monthsOffset option by providing a function that resets it to show the current months.
