### ISSUE TITLE
How to clear dates values

### ISSUE THREAD

**Issue by LoAlbume** [kbwood/datepick#38]
Hi, i'm developing a project with this plugin but i have some troubles:
when i select the first date of a range, i check if the next 7 days are in an array containing some dates. If the selected date is in it, i need take the datepicker back to the initial state where no date is selected... I'm trying create a function for the "onSelect" option, but I don't know how to clear everything. How can I do it?

Thank you.

**Comment by kbwood** [comment]
You can use the _clear_ command:

`$(this).datepick('clear');`
