### ISSUE TITLE
Add days 

### ISSUE THREAD

**Issue by AmineHamrouni** [kbwood/datepick#43]
I want to make the _minDate_ of the **#endPicker** equal to the **#startPicker** value + _5 days_.

`$('#endPicker').datepick('option', 'minDate', $('#startPicker') /*+ 5 days*/); `

I have trouble to use the add function, can you help me, please?

**Comment by kbwood** [comment]
You would do this through code in response to selecting a start date:

```
$('#startPicker').datepick({..., onSelect: function(dates) {
    var date = dates[0];
    if (date) {
        date.setDate(date.getDate() + 5);
    }
    $('#endPicker').datepick('option', {minDate: date});
}});
```
