### ISSUE TITLE
how can i return dates list, between to dates?

### ISSUE THREAD

**Issue by ElawadyNet** [kbwood/datepick#45]
how can i return dates list, between to dates? ex.
[
"Wed Aug 02 2017 12:00:00",
"Wed Aug 03 2017 12:00:00",
"Wed Aug 04 2017 12:00:00",
"Wed Aug 05 2017 12:00:00",
]
or alike

**Comment by kbwood** [comment]
```
var d1 = new Date(2017, 8-1, 2, 12, 0, 0)
var d2 = new Date(2017, 8-1, 5, 12, 0, 0)
var d = new Date(d1.getTime())
var dates = []
while (d.getTime() <= d2.getTime()) {
	dates.push(new Date(d.getTime()))
	d.setDate(d.getDate() + 1)
}
console.log(dates)
```

**Comment by ElawadyNet** [comment]
no, i need the list between selected dates in date range, i use another calendar.

**Comment by ElawadyNet** [comment]
thanks, i did it with adding feature in calendars page in [Adding tab](http://keith-wood.name/calendars.html#add).
