### ISSUE TITLE
Scroll Offset to calendar 

### ISSUE THREAD

**Issue by aakankshkarma** [kbwood/datepick#46]
Hi

I have a calendar on the Middle of the page www.example.com/location when I come on this page from another page the scroll is middle of the page where is my calendar instead of the top of the page as normal behavior.

I check with option i can not get offset 0

**Comment by kbwood** [comment]
What is the URL of your page?

**Comment by aakankshkarma** [comment]
http://mywebdemo.online/yoursmile/location/ i disable the 
.datepick-nav {
    display: none !important;
}
Now it is working but this is not correct way i know

**Comment by kbwood** [comment]
I don't see the scroll effect you mentioned. Disabling display of that section of the calendar should have no effect on scrolling.

**Comment by aakankshkarma** [comment]
Now check

http://mywebdemo.online/yoursmile/location/

**Comment by kbwood** [comment]
The plugin does a focus on the first input element for an inline calendar when loading - as part of persisting focus when an inline calendar updates. The easiest solution is probably just to scroll back to the top of the page after initialising the datepicker. I'll correct it in a future release.

`$(window).scrollTop(0)`

**Comment by aakankshkarma** [comment]
yes thank that work perfect on my end

thanks
